"""
WebSocket endpoint and authoritative real-time game loop.

Streak/combo multiplier (Milestone 19):
  base = 500–1000 pts based on speed
  multiplier = min(1.0 + (streak // 3) * 0.5, 3.0)
  streak 0-2 → ×1.0 | 3-5 → ×1.5 | 6-8 → ×2.0 | 9-11 → ×2.5 | 12+ → ×3.0

Team mode (Milestone 20):
  Rooms are always created as 'classic' (so anyone can join via code).
  Inside the lobby, the host can toggle to 'team' mode. The set_lobby_mode
  action updates room.play_mode and broadcasts the change to all guests.
  Players self-assign via join_team. Topics are set per team via set_team_info.
  start_game accepts play_mode from the message to allow this override.

Security hardening (Milestone 29):
  - All WS inputs go through app.core.sanitize before use
  - action field validated against an explicit allowlist
  - topic validated for prompt-injection patterns
  - X-Forwarded-For uses last-IP (Cloud Run's insertion), not first
  - time_ms clamped to [0, time_limit_ms + 500ms grace]

Cost-abuse hardening (Milestone 39):
  - Generation tickets are now required for ANY non-Quick-Pick topic,
    regardless of play mode (previously only Classic/Team required a
    ticket, leaving Solo mode able to hit Gemini for free with only a
    weak per-IP rate limit protecting it). Quick Pick topics remain free
    and sign-in-free in every mode. (Temporarily, Quick Picks are also
    generated by Gemini to keep them fresh until the per-topic question
    bank is ready.)

Reconnect resilience (Milestone 39):
  - Cloud Run's request timeout caps how long a single WebSocket connection
    may stay open, counted from when the socket first connects (i.e. from
    lobby join), not from when the quiz starts. A long lobby wait plus a
    full-length game can exceed that cap, causing Cloud Run to force-close
    the connection mid-game. Because the client's countdown timer is driven
    locally (Date.now()), it keeps ticking even after the socket dies,
    which looks like a frozen game.
  - On reconnect (same player name rejoining an active room), the server
    now resends the current round's message (QUESTION / ANSWER_REVEAL /
    INTERMISSION_LEADERBOARD) with time recomputed for what's actually
    left, so a client that auto-reconnects picks the round back up instead
    of freezing.
"""

import asyncio
import json
import logging
import random
import time
from typing import Any

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from app.core.state import rooms
from app.core.limiter import is_rate_limited, extract_real_ip_from_ws
from app.core.sanitize import (
    validate_action,
    validate_topic,
    validate_choice,
    validate_time_ms,
    validate_team_id,
    validate_play_mode,
    validate_game_mode,
    sanitize_string,
    MAX_TOPIC_LEN,
    MAX_TEAM_NAME,
)
from app.models.quiz import (
    DEFAULT_GAME_MODE,
    Question,
    GameMode,
    GameStatus,
    PlayMode,
    Player,
    RoundPhase,
    time_limit_for_mode,
)
from app.services.ai import generate_questions, FALLBACK_QUESTIONS
from app.services.profiles import (
    ROOM_ENTRY_FEE,
    apply_delta,
    apply_batch_deltas,
    can_afford_entry,
    solo_rewards,
)
from app.services.powerups import (
    DUEL_MAX_POWERUPS_PER_MATCH,
    FREEZE_BONUS_SECONDS,
    POWERUP_CATALOG,
    STEAL_SECONDS,
    allowed_in_mode,
    consume as consume_powerup,
)
from app.services.tickets import TicketError, refund_generation, use_generation
from app.services.quick_picks import (
    QUICK_PICK_TOPICS,
    is_quick_pick_topic,
    get_quick_pick_questions,
)
from app.services.duels import (
    DUEL_BOT_WIN_COINS,
    DUEL_QUESTION_COUNT,
    DUEL_RESERVE_QUESTIONS,
    DUEL_SUDDEN_DEATH_MAX,
    DUEL_TROPHY_LOSS,
    DUEL_TROPHY_WIN,
    bot_answer_choice,
    bot_answer_delay_secs,
    duel_winner_name,
    record_h2h_win,
)

logger = logging.getLogger(__name__)
router = APIRouter()

BASE_POINTS                      = 1000
ANSWER_REVEAL_SECONDS            = 4
INTERMISSION_LEADERBOARD_SECONDS = 5
GENERATION_TIMEOUT_SECONDS       = 30
REJOIN_MIN_REMAINING_MS          = 1000  # floor so a reconnect never insta-expires

_round_timeout_tasks: dict[str, asyncio.Task] = {}

# Tracks which rooms are currently mid-resolve to prevent duplicate concurrent
# calls to resolve_round() (e.g. from expire_question + answer handler racing).
_resolving_rounds: set[str] = set()


# ── Broadcast helpers ─────────────────────────────────────────────────────────

async def broadcast(room_code: str, message: dict[str, Any]) -> None:
    """Send a JSON message to every connected player in a room in parallel."""
    room = rooms.get(room_code)
    if not room:
        return

    encoded_message = json.dumps(message)
    tasks = []
    player_names = []

    for name, player in list(room.players.items()):
        if player.websocket is not None:
            tasks.append(player.websocket.send_text(encoded_message))
            player_names.append(name)

    if not tasks:
        return

    results = await asyncio.gather(*tasks, return_exceptions=True)

    dead: list[str] = []
    for i, result in enumerate(results):
        if isinstance(result, Exception):
            name = player_names[i]
            dead.append(name)
            logger.warning(
                "Failed to send message to '%s' in room '%s': %s", name, room_code, result
            )

    for name in dead:
        player = room.players.get(name)
        if player:
            player.websocket = None
        logger.warning(
            "Marked player '%s' as disconnected in room '%s' due to send failure",
            name,
            room_code,
        )


async def send_to(websocket: WebSocket, message: dict[str, Any]) -> None:
    """Send one JSON message to one WebSocket connection."""
    await websocket.send_text(json.dumps(message))


async def _delayed_room_cleanup(room_code: str, delay: int = 60) -> None:
    """Delete a room if it stays empty after a grace period."""
    await asyncio.sleep(delay)
    room = rooms.get(room_code)
    if not room:
        return
    if not any(p.websocket is not None for p in room.players.values()):
        _cancel_round_timeout(room_code)
        rooms.pop(room_code, None)
        logger.info("Room '%s' deleted after grace period", room_code)


def _cancel_round_timeout(room_code: str) -> None:
    task = _round_timeout_tasks.pop(room_code, None)
    if task and task is not asyncio.current_task():
        task.cancel()


# ── Scoring ───────────────────────────────────────────────────────────────────

def calculate_score(time_ms: int, time_limit_ms: int, streak: int) -> int:
    """
    Base score 500–1000 (speed-based) × streak multiplier.

    Multiplier thresholds (streak // 3):
      0 (0-2)  → ×1.0
      1 (3-5)  → ×1.5
      2 (6-8)  → ×2.0
      3 (9-11) → ×2.5
      4+ (12+) → ×3.0
    """
    clamped = max(0, min(time_ms, time_limit_ms))
    base = int(BASE_POINTS * (1 - (clamped / time_limit_ms) * 0.5))
    base = max(500, min(1000, base))
    multiplier = min(1.0 + (streak // 3) * 0.5, 3.0)
    return int(base * multiplier)


# Duel scoring (Milestone 64): the near-continuous 500–1000 speed curve made
# exact score ties (and therefore sudden death) practically impossible in
# head-to-head play. Duels instead use coarse tiers so equal-skill matches
# genuinely land on equal scores. No streak multiplier — 10 questions is too
# short for streak math to feel fair, and it multiplies away tie-ability.
DUEL_BASE_CORRECT      = 100
DUEL_FAST_BONUS        = 50   # answered within first 1/3 of the timer
DUEL_MID_BONUS         = 25   # within first 2/3
DUEL_FINAL_STRETCH_Q   = 3    # last N main questions are worth double
DUEL_FINAL_STRETCH_MUL = 2


def duel_speed_tier(time_ms: int, time_limit_ms: int) -> str:
    clamped = max(0, min(time_ms, time_limit_ms))
    if clamped <= time_limit_ms / 3:
        return "fast"
    if clamped <= time_limit_ms * 2 / 3:
        return "mid"
    return "slow"


def calculate_duel_score(time_ms: int, time_limit_ms: int) -> tuple[int, str]:
    """Return (points, speed_tier) for a correct duel answer."""
    tier  = duel_speed_tier(time_ms, time_limit_ms)
    bonus = {"fast": DUEL_FAST_BONUS, "mid": DUEL_MID_BONUS}.get(tier, 0)
    return DUEL_BASE_CORRECT + bonus, tier


def _duel_is_final_stretch(room) -> bool:
    """Last 3 questions of the MAIN duel set (never sudden-death extras)."""
    return (
        room.play_mode == PlayMode.DUEL
        and room.current_q_index >= DUEL_QUESTION_COUNT - DUEL_FINAL_STRETCH_Q
        and room.current_q_index < DUEL_QUESTION_COUNT
    )


# ── Team helpers ──────────────────────────────────────────────────────────────

def _team_scores(room) -> dict[str, int]:
    """Aggregate individual player scores into per-team totals."""
    totals: dict[str, int] = {tid: 0 for tid in room.team_names}
    for pname, player in room.players.items():
        tid = room.teams.get(pname)
        if tid in totals:
            totals[tid] += player.score
    return totals


def _round_payload(room) -> dict[str, Any]:
    """Common answer/score payload for ANSWER_REVEAL and INTERMISSION_LEADERBOARD."""
    question = room.questions[room.current_q_index]
    payload: dict[str, Any] = {
        "scores":        {n: p.score for n, p in room.players.items()},
        "points_gained": dict(room.points_gained),
        "answers":       dict(room.answers_this_round),
        "correct_index": question.correct_index,
        "play_mode":     room.play_mode.value,
        "streaks":       {n: p.streak for n, p in room.players.items()},
    }
    if room.play_mode == PlayMode.DUEL:
        payload["speed_tiers"] = dict(room.round_speed_tiers)
        payload["final_stretch"] = _duel_is_final_stretch(room)
    if room.play_mode == PlayMode.TEAM:
        payload["team_scores"] = _team_scores(room)
        payload["teams"]       = dict(room.teams)
        payload["team_names"]  = dict(room.team_names)
    return payload


def _connected_players(room) -> list[Player]:
    """Return players who are currently attached to an open WebSocket."""
    return [p for p in room.players.values() if p.websocket is not None]


def _insufficient_coin_names(room) -> list[str]:
    """Return connected players who cannot pay the room entry fee."""
    names: list[str] = []
    for player in _connected_players(room):
        if player.user_id and not can_afford_entry(player.user_id):
            names.append(player.name)
    return names


def _charge_room_entry_fees(room) -> None:
    """Deduct the multiplayer entry fee once at session start."""
    room.entry_fees = {}
    for player in _connected_players(room):
        if not player.user_id:
            continue
        apply_delta(player.user_id, coins_delta=-ROOM_ENTRY_FEE)
        room.entry_fees[player.name] = float(ROOM_ENTRY_FEE)


def _refund_room_entry_fees(room) -> None:
    """Refund all charged entry fees if quiz startup fails."""
    for name, fee in room.entry_fees.items():
        player = room.players.get(name)
        if player and player.user_id:
            apply_delta(player.user_id, coins_delta=fee)
    room.entry_fees = {}


def _refund_generation_ticket(room) -> None:
    """Refund the host's generation (free allowance or ticket) if quiz startup fails."""

    user_id = getattr(room, "generation_ticket_user_id", None)
    source  = getattr(room, "generation_source", None)
    if user_id:
        refund_generation(user_id, source or "ticket")
        room.generation_ticket_user_id = None
        room.generation_source = None


def _finalize_economy(
    room, final_scores: dict[str, int], correct_answers: dict[str, int]
) -> dict[str, Any]:
    """Apply end-of-game economy rules and return per-player UI payloads."""
    if room.economy_finalized:
        return {}

    economy: dict[str, Any] = {}
    deltas_to_apply = {}

    if room.play_mode == PlayMode.SOLO:
        for name, player in room.players.items():
            if not player.user_id:
                continue
            correct = int(correct_answers.get(name, 0))
            coins_delta, trophies_delta = solo_rewards(correct)
            deltas_to_apply[player.user_id] = {
                "coins_delta":    coins_delta,
                "trophies_delta": trophies_delta,
                "player_name":    name,
            }
    elif room.play_mode in (PlayMode.CLASSIC, PlayMode.TEAM):
        pool = float(sum(room.entry_fees.values()))
        paid_scores = {
            name: final_scores.get(name, 0)
            for name in room.entry_fees
            if name in final_scores
        }
        if paid_scores and pool > 0:
            top_score = max(paid_scores.values())
            winners   = [n for n, s in paid_scores.items() if s == top_score]
            payout    = pool / len(winners) if winners else 0
            for name in winners:
                player = room.players.get(name)
                if not player or not player.user_id:
                    continue
                entry_fee = room.entry_fees.get(name, 0)
                deltas_to_apply[player.user_id] = {
                    "coins_delta":    payout,
                    "trophies_delta": 0,
                    "player_name":    name,
                    "is_winner":      True,
                    "payout":         payout,
                    "entry_fee":      entry_fee,
                }
            for name, fee in room.entry_fees.items():
                player = room.players.get(name)
                if not player or not player.user_id or player.user_id in deltas_to_apply:
                    continue
                deltas_to_apply[player.user_id] = {
                    "coins_delta":    0,
                    "trophies_delta": 0,
                    "player_name":    name,
                    "is_winner":      False,
                    "entry_fee":      fee,
                }

    elif room.play_mode == PlayMode.DUEL:
        winner = duel_winner_name(room)
        if room.duel_is_bot:
            # Practice match: no fees, no trophies — small consolation coins
            # for beating the bot so the fallback still feels worth playing.
            human = next((p for p in room.players.values() if p.user_id), None)
            if human:
                won = winner == human.name
                deltas_to_apply[human.user_id] = {
                    "coins_delta":    DUEL_BOT_WIN_COINS if won else 0.0,
                    "trophies_delta": 0,
                    "player_name":    human.name,
                    "is_winner":      won,
                    "payout":         DUEL_BOT_WIN_COINS if won else 0.0,
                    "entry_fee":      0.0,
                }
        else:
            pool = float(sum(room.entry_fees.values()))
            for name, player in room.players.items():
                if not player.user_id:
                    continue
                fee = room.entry_fees.get(name, 0.0)
                if winner is None:
                    # Sudden death exhausted with scores still level → refund
                    # both fees, no trophy movement. Nobody loses on a draw.
                    deltas_to_apply[player.user_id] = {
                        "coins_delta":    fee,
                        "trophies_delta": 0,
                        "player_name":    name,
                        "is_winner":      False,
                        "is_draw":        True,
                        "payout":         fee,
                        "entry_fee":      fee,
                    }
                elif name == winner:
                    deltas_to_apply[player.user_id] = {
                        "coins_delta":    pool,
                        "trophies_delta": DUEL_TROPHY_WIN,
                        "player_name":    name,
                        "is_winner":      True,
                        "payout":         pool,
                        "entry_fee":      fee,
                    }
                else:
                    deltas_to_apply[player.user_id] = {
                        "coins_delta":    0.0,
                        "trophies_delta": DUEL_TROPHY_LOSS,
                        "player_name":    name,
                        "is_winner":      False,
                        "payout":         0.0,
                        "entry_fee":      fee,
                    }
            if winner is not None:
                ids = {n: p.user_id for n, p in room.players.items() if p.user_id}
                loser = next((n for n in ids if n != winner), None)
                if loser and winner in ids:
                    record_h2h_win(ids[winner], ids[loser])

    if deltas_to_apply:
        from app.services.profiles import get_profile
        profiles_before  = {uid: get_profile(uid) for uid in deltas_to_apply}
        updated_profiles = apply_batch_deltas(deltas_to_apply)

        for user_id, profile_after in updated_profiles.items():
            info           = deltas_to_apply[user_id]
            name           = info["player_name"]
            profile_before = profiles_before[user_id]
            if room.play_mode == PlayMode.SOLO:
                economy[name] = {
                    "coins_delta":    info["coins_delta"],
                    "trophies_delta": profile_after["trophies"] - profile_before["trophies"],
                    "coins":          profile_after["coins"],
                    "trophies":       profile_after["trophies"],
                }
            elif room.play_mode == PlayMode.DUEL:
                economy[name] = {
                    # Net vs the pre-game balance: winner +25, loser -25,
                    # draw 0 (fee refunded), bot win +consolation.
                    "coins_delta":    info["payout"] - info["entry_fee"],
                    "trophies_delta": profile_after["trophies"] - profile_before["trophies"],
                    "coins":          profile_after["coins"],
                    "trophies":       profile_after["trophies"],
                    "entry_fee":      info["entry_fee"],
                    "payout":         info["payout"],
                    "is_winner":      info.get("is_winner", False),
                    "is_draw":        info.get("is_draw", False),
                    "is_bot_match":   room.duel_is_bot,
                }
            else:
                if info.get("is_winner"):
                    economy[name] = {
                        "coins_delta":    info["payout"] - info["entry_fee"],
                        "trophies_delta": 0,
                        "coins":          profile_after["coins"],
                        "trophies":       profile_after["trophies"],
                        "entry_fee":      info["entry_fee"],
                        "payout":         info["payout"],
                    }
                else:
                    economy[name] = {
                        "coins_delta":    -info["entry_fee"],
                        "trophies_delta": 0,
                        "coins":          profile_after["coins"],
                        "trophies":       profile_after["trophies"],
                        "entry_fee":      info["entry_fee"],
                    }

    room.economy_finalized = True
    return economy


# ── Round lifecycle ───────────────────────────────────────────────────────────

async def _expire_question(room_code: str, question_index: int) -> None:
    """Resolve a round when the timer runs out server-side."""
    try:
        room = rooms.get(room_code)
        if not room:
            return
        await asyncio.sleep((room.time_limit_ms / 1000) + 3)
        await resolve_round(room_code, question_index)
    except asyncio.CancelledError:
        return


async def _expire_question_in(room_code: str, question_index: int, delay_secs: float) -> None:
    """Re-armed round timeout with an explicit delay (used by TIME_FREEZE)."""
    try:
        await asyncio.sleep(max(0.5, delay_secs))
        await resolve_round(room_code, question_index)
    except asyncio.CancelledError:
        return


async def broadcast_question(room_code: str) -> None:
    """Broadcast the current question and arm the server-side timeout."""
    room     = rooms[room_code]
    question = room.questions[room.current_q_index]
    room.phase = RoundPhase.QUESTION
    room.answers_this_round = {}
    room.points_gained = {name: 0 for name in room.players}
    room.question_started_at = time.time()
    room.round_powerups_used = set()
    room.double_points_active = set()
    room.round_extra_secs = 0.0
    room.round_speed_tiers = {}
    for player in room.players.values():
        player.answered    = False
        player.last_answer = None

    msg_data: dict[str, Any] = {
        "index":         room.current_q_index,
        "text":          question.question,
        "options":       question.options,
        "mode":          room.mode.value,
        "play_mode":     room.play_mode.value,
        "phase":         room.phase.value,
        "time_limit_ms": room.time_limit_ms,
    }
    if room.play_mode == PlayMode.DUEL:
        msg_data["final_stretch"] = _duel_is_final_stretch(room)
    if room.play_mode == PlayMode.TEAM:
        msg_data["team_scores"] = _team_scores(room)
        msg_data["teams"]       = dict(room.teams)
        msg_data["team_names"]  = dict(room.team_names)

    await broadcast(room_code, {"type": "QUESTION", "data": msg_data})
    _cancel_round_timeout(room_code)
    _round_timeout_tasks[room_code] = asyncio.create_task(
        _expire_question(room_code, room.current_q_index)
    )


async def _send_rejoin_resync(websocket: WebSocket, room) -> None:
    """
    Bring a reconnecting player back up to speed on the current round.

    Reuses the exact same message shapes as the live broadcasts (QUESTION /
    ANSWER_REVEAL / INTERMISSION_LEADERBOARD) so the client's existing
    handlers work unmodified — the client's WS._pending queue already
    handles the case where this arrives before the screen has registered
    its handlers.

    For an in-progress QUESTION, time_limit_ms is recomputed to reflect what
    is actually left rather than resending the full original duration, so a
    reconnecting client's local countdown lines back up with the server's
    authoritative round timer (which keeps running server-side regardless
    of any single player's connection state).
    """
    if room.status != GameStatus.ACTIVE:
        return

    if room.phase == RoundPhase.QUESTION:
        elapsed_ms   = max(0.0, (time.time() - room.question_started_at) * 1000)
        remaining_ms = max(REJOIN_MIN_REMAINING_MS, int(room.time_limit_ms - elapsed_ms))
        question     = room.questions[room.current_q_index]
        msg_data: dict[str, Any] = {
            "index":         room.current_q_index,
            "text":          question.question,
            "options":       question.options,
            "mode":          room.mode.value,
            "play_mode":     room.play_mode.value,
            "phase":         room.phase.value,
            "time_limit_ms": remaining_ms,
        }
        if room.play_mode == PlayMode.TEAM:
            msg_data["team_scores"] = _team_scores(room)
            msg_data["teams"]       = dict(room.teams)
            msg_data["team_names"]  = dict(room.team_names)
        await send_to(websocket, {"type": "QUESTION", "data": msg_data})

    elif room.phase in (RoundPhase.ANSWER_REVEAL, RoundPhase.INTERMISSION_LEADERBOARD):
        payload = _round_payload(room)
        payload.update({"phase": room.phase.value, "hold_ms": 1000})
        if room.phase == RoundPhase.INTERMISSION_LEADERBOARD:
            payload["is_final"] = room.current_q_index + 1 >= len(room.questions)
            msg_type = "INTERMISSION_LEADERBOARD"
        else:
            msg_type = "ANSWER_REVEAL"
        await send_to(websocket, {"type": msg_type, "data": payload})


async def resolve_round(room_code: str, question_index: int) -> None:
    """Lock the round and drive the reveal → intermission → next-question sequence.

    WHY the _resolving_rounds guard:
      resolve_round() can be triggered from two concurrent paths for the same
      round — the player answer handler and the _expire_question timeout task.
      Both paths check room.phase == QUESTION before entering, but because Python
      async code yields at every 'await', both can pass that check before either
      has had the chance to mutate room.phase.  The result was two concurrent
      coroutines both sleeping through the ANSWER_REVEAL and INTERMISSION phases,
      then both advancing current_q_index and broadcasting the next question,
      which corrupted state and froze the game loop.

      The set acts as a fast, non-async mutex: the first caller wins, any
      subsequent concurrent call for the same room returns immediately.
    """
    # ── Concurrency guard — only one resolve may run per room at a time ────────
    if room_code in _resolving_rounds:
        logger.debug(
            "resolve_round(%s, q=%d) skipped — already resolving",
            room_code, question_index,
        )
        return

    room = rooms.get(room_code)
    if (
        not room
        or room.status != GameStatus.ACTIVE
        or room.phase  != RoundPhase.QUESTION
        or room.current_q_index != question_index
    ):
        return

    # Claim the lock and cancel any pending expire task for this room.
    # Cancelling here (rather than in the callers) guarantees the task is always
    # stopped before we mutate room state, regardless of which path won the race.
    _resolving_rounds.add(room_code)
    _cancel_round_timeout(room_code)

    try:
        for name, player in room.players.items():
            if name not in room.answers_this_round:
                player.streak = 0

        room.phase   = RoundPhase.ANSWER_REVEAL
        reveal_data  = _round_payload(room)
        reveal_data.update({"phase": room.phase.value, "hold_ms": ANSWER_REVEAL_SECONDS * 1000})
        await broadcast(room_code, {"type": "ANSWER_REVEAL", "data": reveal_data})
        await asyncio.sleep(ANSWER_REVEAL_SECONDS)

        room = rooms.get(room_code)
        if not room or room.status != GameStatus.ACTIVE:
            return

        if room.play_mode in (PlayMode.CLASSIC, PlayMode.TEAM):
            room.phase = RoundPhase.INTERMISSION_LEADERBOARD
            is_final   = room.current_q_index + 1 >= len(room.questions)
            hold_secs  = 2 if is_final else INTERMISSION_LEADERBOARD_SECONDS
            inter_data = _round_payload(room)
            inter_data.update({
                "phase":    room.phase.value,
                "hold_ms":  hold_secs * 1000,
                "is_final": is_final,
            })
            await broadcast(room_code, {"type": "INTERMISSION_LEADERBOARD", "data": inter_data})
            await asyncio.sleep(hold_secs)

        room = rooms.get(room_code)
        if not room or room.status != GameStatus.ACTIVE:
            return

        if room.current_q_index + 1 >= len(room.questions):
            await _finish_game(room_code)
            return

        room.current_q_index += 1
        await broadcast_question(room_code)
        _maybe_schedule_bot_answer(room_code)

    finally:
        # Always release the lock so future rounds in the same room can proceed.
        _resolving_rounds.discard(room_code)


def _reset_room_for_rematch(room) -> None:
    """Return a finished duel room to the topic-pick phase for a rematch."""
    room.status               = GameStatus.WAITING
    room.phase                = RoundPhase.LOBBY
    room.questions            = []
    room.current_q_index      = 0
    room.answers_this_round   = {}
    room.points_gained        = {}
    room.entry_fees           = {}
    room.economy_finalized    = False
    room.duel_reserves        = []
    room.sudden_death_count   = 0
    room.duel_forfeit_winner  = ""
    room.duel_picks           = {}
    room.duel_rematch_votes   = set()
    from app.services.duels import _duel_topic_options
    room.duel_topic_options   = _duel_topic_options()
    for p in room.players.values():
        p.score = 0; p.correct_answers = 0; p.streak = 0
        p.answered = False; p.last_answer = None


async def _start_duel_game(room_code: str, delay: float) -> None:
    """Charge fees, draw bank questions, and launch a duel after the confirm pause.

    Runs as a detached task so the pick handler returns immediately; every
    failure path unwinds cleanly back to WAITING with fees refunded.
    """
    await asyncio.sleep(delay)
    room = rooms.get(room_code)
    if not room or room.status != GameStatus.WAITING or room.play_mode != PlayMode.DUEL:
        return

    if not room.duel_is_bot:
        broke = _insufficient_coin_names(room)
        if broke:
            await broadcast(room_code, {
                "type": "ERROR",
                "data": {"message": f"Not enough coins: {', '.join(broke)}"},
            })
            room.duel_picks = {}
            return
        _charge_room_entry_fees(room)

    room.status = GameStatus.STARTING
    try:
        # Main set + sudden-death reserves in one draw, so a tiebreaker can
        # never fail mid-duel on a thin bank. Duels are bank-only by design:
        # zero Gemini cost, and both players provably get identical questions.
        combined = get_quick_pick_questions(
            room.topic, DUEL_QUESTION_COUNT + DUEL_RESERVE_QUESTIONS
        )
        room.questions     = combined[:DUEL_QUESTION_COUNT]
        room.duel_reserves = combined[DUEL_QUESTION_COUNT:]
    except ValueError as exc:
        logger.error("Duel question draw failed for room '%s': %s", room_code, exc)
        if room.entry_fees:
            _refund_room_entry_fees(room)
        room.status = GameStatus.WAITING
        room.duel_picks = {}
        await broadcast(room_code, {
            "type": "ERROR",
            "data": {"message": "Could not load questions for that topic. Pick again."},
        })
        return

    await broadcast(room_code, {
        "type": "GAME_STARTING",
        "data": {
            "topic":           room.topic,
            "mode":            room.mode.value,
            "play_mode":       room.play_mode.value,
            "time_limit_ms":   room.time_limit_ms,
            "total_questions": len(room.questions),
        },
    })

    for p in room.players.values():
        p.score = 0; p.correct_answers = 0; p.streak = 0
    room.status          = GameStatus.ACTIVE
    room.current_q_index = 0
    await broadcast_question(room_code)
    _maybe_schedule_bot_answer(room_code)


def _required_answer_count(room) -> int:
    """How many answers must arrive before a round can resolve early.

    The practice bot has no WebSocket, so _connected_players() never counts
    it — without this, a lone human answering would instantly resolve the
    round before the bot's scheduled answer lands.
    """
    count = len(_connected_players(room))
    if room.play_mode == PlayMode.DUEL and room.duel_is_bot:
        count += 1
    return count


def _maybe_schedule_bot_answer(room_code: str) -> None:
    """Arm the practice bot's answer task for the just-broadcast question."""
    room = rooms.get(room_code)
    if not room or room.play_mode != PlayMode.DUEL or not room.duel_is_bot:
        return
    asyncio.create_task(_bot_answer_task(room_code, room.current_q_index))


async def _bot_answer_task(room_code: str, question_index: int) -> None:
    """Have the bot answer after a human-feeling delay, then maybe resolve."""
    delay = bot_answer_delay_secs()
    await asyncio.sleep(delay)
    room = rooms.get(room_code)
    if (
        not room
        or room.status != GameStatus.ACTIVE
        or room.phase != RoundPhase.QUESTION
        or room.current_q_index != question_index
    ):
        return
    bot = room.players.get(room.duel_bot_name)
    if not bot or bot.name in room.answers_this_round:
        return

    question = room.questions[question_index]
    choice = bot_answer_choice(room, question.correct_index)
    if choice == question.correct_index:
        bot.streak += 1
        points, tier = calculate_duel_score(int(delay * 1000), room.time_limit_ms)
        if _duel_is_final_stretch(room):
            points *= DUEL_FINAL_STRETCH_MUL
        room.round_speed_tiers[bot.name] = tier
        bot.correct_answers += 1
    else:
        bot.streak = 0
        points = 0
    bot.score += points
    bot.answered = True
    bot.last_answer = choice
    room.answers_this_round[bot.name] = choice
    room.points_gained[bot.name] = points

    await broadcast(room_code, {
        "type": "DUEL_PLAYER_ANSWERED",
        "data": {"name": bot.name},
    })

    if len(room.answers_this_round) >= _required_answer_count(room):
        _cancel_round_timeout(room_code)
        await resolve_round(room_code, question_index)


async def _duel_forfeit_check(room_code: str, leaver_name: str, grace_secs: float = 25.0) -> None:
    """End an active duel by forfeit if the leaver never reconnects."""
    await asyncio.sleep(grace_secs)
    room = rooms.get(room_code)
    if not room or room.status != GameStatus.ACTIVE or room.play_mode != PlayMode.DUEL:
        return
    leaver = room.players.get(leaver_name)
    if not leaver or leaver.websocket is not None:
        return  # they made it back — play on
    stayer = next(
        (n for n, p in room.players.items() if n != leaver_name and p.websocket is not None),
        None,
    )
    if not stayer:
        return  # both gone — normal cleanup will collect the room
    room.duel_forfeit_winner = stayer
    _cancel_round_timeout(room_code)
    logger.info("Duel room '%s': '%s' wins by forfeit ('%s' left)", room_code, stayer, leaver_name)
    await _finish_game(room_code)


async def _finish_game(room_code: str) -> None:
    """Broadcast final results once all questions are done."""
    room = rooms.get(room_code)
    if not room:
        return

    # ── Duel sudden death ─────────────────────────────────────────────────────
    # A duel that ends level gets one extra bank question at a time (drawn
    # from the reserve set fetched at start) until someone leads or the
    # reserve/attempt cap runs out — a mode about "who's better" shouldn't
    # end in a shrug. Forfeits skip this: the remaining player already won.
    if (
        room.play_mode == PlayMode.DUEL
        and not room.duel_forfeit_winner
        and duel_winner_name(room) is None
        and room.duel_reserves
        and room.sudden_death_count < DUEL_SUDDEN_DEATH_MAX
    ):
        room.sudden_death_count += 1
        extra = room.duel_reserves.pop(0)
        room.questions.append(extra)
        room.current_q_index = len(room.questions) - 1
        await broadcast(room_code, {
            "type": "SUDDEN_DEATH",
            "data": {
                "round":  room.sudden_death_count,
                "scores": {n: p.score for n, p in room.players.items()},
            },
        })
        await asyncio.sleep(2.5)  # let the banner land before the question
        room = rooms.get(room_code)
        if not room or room.status != GameStatus.ACTIVE:
            return
        await broadcast_question(room_code)
        _maybe_schedule_bot_answer(room_code)
        return

    room.status = GameStatus.FINISHED
    room.phase  = RoundPhase.COMPLETE
    total           = len(room.questions)
    final_scores    = {n: p.score           for n, p in room.players.items()}
    correct_answers = {n: p.correct_answers for n, p in room.players.items()}
    accuracy_pct    = {
        n: round((c / total) * 100) if total else 0
        for n, c in correct_answers.items()
    }
    economy   = _finalize_economy(room, final_scores, correct_answers)
    game_over: dict[str, Any] = {
        "final_scores":         final_scores,
        "correct_answers":      correct_answers,
        "accuracy_percentages": accuracy_pct,
        "total_questions":      total,
        "play_mode":            room.play_mode.value,
        "economy":              economy,
    }
    if room.play_mode == PlayMode.SOLO:
        # Include the frozen question set so the client can offer "Challenge
        # a Friend" without a follow-up request depending on this room still
        # being in THIS Cloud Run instance's memory — a later HTTP request
        # can land on a different instance that never saw this room at all.
        # No new leakage: each question's correct_index was already sent to
        # this client during its own ANSWER_REVEAL earlier in the game.
        game_over["topic"]         = room.topic
        game_over["mode"]          = room.mode.value
        game_over["time_limit_ms"] = room.time_limit_ms
        game_over["questions"]     = [q.model_dump() for q in room.questions]
    if room.play_mode == PlayMode.DUEL:
        game_over["topic"]              = room.topic
        game_over["duel_winner"]        = duel_winner_name(room)
        game_over["is_forfeit"]         = bool(room.duel_forfeit_winner)
        game_over["sudden_death_count"] = room.sudden_death_count
        game_over["is_bot_match"]       = room.duel_is_bot
    if room.play_mode == PlayMode.TEAM:
        game_over["team_scores"] = _team_scores(room)
        game_over["teams"]       = dict(room.teams)
        game_over["team_names"]  = dict(room.team_names)
    await broadcast(room_code, {"type": "GAME_OVER", "data": game_over})
    logger.info("Game over in room '%s'. Scores: %s", room_code, final_scores)


# ── WebSocket endpoint ────────────────────────────────────────────────────────

@router.websocket("/ws/{room_code}/{player_name}")
async def websocket_endpoint(
    websocket: WebSocket,
    room_code: str,
    player_name: str,
    user_id: str | None = None,
) -> None:
    """Accept a player and process room actions until the socket disconnects."""

    await websocket.accept()

    # ── Rate-limit new WS connections ─────────────────────────────────────────
    ip = extract_real_ip_from_ws(websocket)
    if is_rate_limited(ip, action="ws_join"):
        await send_to(websocket, {
            "type": "ERROR",
            "data": {"message": "Too many connection attempts. Please wait a moment."},
        })
        await websocket.close()
        return

    room = rooms.get(room_code)
    if not room:
        await send_to(websocket, {"type": "ERROR", "data": {"message": "Room not found"}})
        await websocket.close()
        return

    # Sanitize the player name from the URL path
    clean_name = sanitize_string(player_name, 20)
    if not clean_name:
        await send_to(websocket, {"type": "ERROR", "data": {"message": "Invalid player name."}})
        await websocket.close()
        return
    player_name = clean_name

    # Re-join support: player reconnects after disconnect
    is_rejoin = False
    existing = room.players.get(player_name)
    if existing:
        if existing.websocket is not None:
            await send_to(websocket, {
                "type": "ERROR",
                "data": {"message": "Name already taken in this room"},
            })
            await websocket.close()
            return
        existing.websocket = websocket
        if user_id:
            existing.user_id = user_id
        is_rejoin = True
        logger.info("Player '%s' re-joined room '%s'", player_name, room_code)
    else:
        if room.status != GameStatus.WAITING:
            await send_to(websocket, {
                "type": "ERROR",
                "data": {"message": "Game already in progress"},
            })
            await websocket.close()
            return
        if room.locked:
            await send_to(websocket, {
                "type": "ERROR",
                "data": {"message": "Room is locked by host"},
            })
            await websocket.close()
            return
        if room.play_mode == PlayMode.SOLO and player_name != room.host:
            await send_to(websocket, {
                "type": "ERROR",
                "data": {"message": "Solo rooms are private"},
            })
            await websocket.close()
            return
        room.players[player_name] = Player(
            name=player_name, user_id=user_id, websocket=websocket
        )
        logger.info("Player '%s' joined room '%s'", player_name, room_code)

    joined_data: dict[str, Any] = {
        "players":    list(room.players.keys()),
        "lobby_mode": room.play_mode.value,
        "locked":     room.locked,
    }
    if room.play_mode == PlayMode.TEAM:
        joined_data["teams"]       = dict(room.teams)
        joined_data["team_names"]  = dict(room.team_names)
        joined_data["team_topics"] = dict(room.team_topics)
    await broadcast(room_code, {"type": "PLAYER_JOINED", "data": joined_data})

    # ── Duel: both players connected → open the topic-pick phase ──────────────
    # Bot rooms only ever have one socket; matched rooms wait for both.
    if room.play_mode == PlayMode.DUEL and room.status == GameStatus.WAITING:
        humans_needed = 1 if room.duel_is_bot else 2
        if len(_connected_players(room)) >= humans_needed and not room.duel_picks:
            await broadcast(room_code, {
                "type": "DUEL_TOPIC_PICK",
                "data": {
                    "options":       list(room.duel_topic_options),
                    "players":       list(room.players.keys()),
                    "bot_name":      room.duel_bot_name,
                    "time_limit_ms": room.time_limit_ms,
                },
            })

    # If this is a reconnect into a game already underway, resync the
    # reconnecting socket with the current round state instead of leaving
    # them stalled until the next natural broadcast.
    if is_rejoin:
        try:
            await _send_rejoin_resync(websocket, room)
        except Exception as exc:
            logger.warning(
                "Rejoin resync failed for '%s' in room '%s': %s", player_name, room_code, exc
            )

    try:
        while True:
            raw = await websocket.receive_text()

            # ── Parse JSON ────────────────────────────────────────────────────
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                await send_to(websocket, {"type": "ERROR", "data": {"message": "Invalid JSON"}})
                continue

            if not isinstance(msg, dict):
                await send_to(websocket, {"type": "ERROR", "data": {"message": "Message must be a JSON object"}})
                continue

            # ── Validate action against allowlist ─────────────────────────────
            action = validate_action(msg.get("action"))
            if action is None:
                raw_action = msg.get("action")
                # Only log if it looks like a real unknown action (not noise)
                if isinstance(raw_action, str):
                    logger.warning(
                        "Unknown/invalid action '%s' from '%s' in room '%s'",
                        raw_action[:64], player_name, room_code,
                    )
                await send_to(websocket, {
                    "type": "ERROR",
                    "data": {"message": "Unknown or invalid action."},
                })
                continue

            # ═════════════════════════════════════════════════════════════════
            # ACTION HANDLERS
            # ═════════════════════════════════════════════════════════════════

            # ── lock_room ─────────────────────────────────────────────────────
            if action == "lock_room":
                if player_name != room.host:
                    continue
                room.locked = True
                await broadcast(room_code, {
                    "type": "PLAYER_JOINED",
                    "data": {
                        "players":     list(room.players.keys()),
                        "lobby_mode":  room.play_mode.value,
                        "locked":      True,
                        "teams":       dict(room.teams),
                        "team_names":  dict(room.team_names),
                        "team_topics": dict(room.team_topics),
                    },
                })

            # ── unlock_room ───────────────────────────────────────────────────
            elif action == "unlock_room":
                if player_name != room.host:
                    continue
                room.locked    = False
                room.play_mode = PlayMode.CLASSIC
                await broadcast(room_code, {
                    "type": "LOBBY_MODE_CHANGED",
                    "data": {
                        "mode":       room.play_mode.value,
                        "locked":     False,
                        "team_names": dict(room.team_names),
                        "teams":      dict(room.teams),
                    },
                })
                await broadcast(room_code, {
                    "type": "PLAYER_JOINED",
                    "data": {
                        "players":     list(room.players.keys()),
                        "lobby_mode":  room.play_mode.value,
                        "locked":      False,
                        "teams":       dict(room.teams),
                        "team_names":  dict(room.team_names),
                        "team_topics": dict(room.team_topics),
                    },
                })

            # ── set_lobby_mode ────────────────────────────────────────────────
            elif action == "set_lobby_mode":
                if player_name != room.host:
                    continue
                if room.status != GameStatus.WAITING:
                    continue
                requested = validate_play_mode(msg.get("mode"), allowed=("classic", "team"))
                if requested is None:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Invalid mode. Must be 'classic' or 'team'."},
                    })
                    continue
                if requested == "team" and not room.locked:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Lock room first to enable Team Mode"},
                    })
                    continue
                room.play_mode = PlayMode(requested)
                name_a = sanitize_string(msg.get("name_a", room.team_names.get("A", "Team A")), MAX_TEAM_NAME) or "Team A"
                name_b = sanitize_string(msg.get("name_b", room.team_names.get("B", "Team B")), MAX_TEAM_NAME) or "Team B"
                room.team_names = {"A": name_a, "B": name_b}
                await broadcast(room_code, {
                    "type": "LOBBY_MODE_CHANGED",
                    "data": {
                        "mode":       room.play_mode.value,
                        "locked":     room.locked,
                        "team_names": dict(room.team_names),
                        "teams":      dict(room.teams),
                    },
                })
                await broadcast(room_code, {
                    "type": "PLAYER_JOINED",
                    "data": {
                        "players":     list(room.players.keys()),
                        "lobby_mode":  room.play_mode.value,
                        "locked":      room.locked,
                        "teams":       dict(room.teams),
                        "team_names":  dict(room.team_names),
                        "team_topics": dict(room.team_topics),
                    },
                })

            # ── join_team ─────────────────────────────────────────────────────
            elif action == "join_team":
                if room.play_mode != PlayMode.TEAM:
                    continue
                team_id = validate_team_id(msg.get("team_id"))
                if team_id is None:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Team must be A or B"},
                    })
                    continue
                room.teams[player_name] = team_id
                await broadcast(room_code, {
                    "type": "PLAYER_JOINED",
                    "data": {
                        "players":     list(room.players.keys()),
                        "lobby_mode":  room.play_mode.value,
                        "teams":       dict(room.teams),
                        "team_names":  dict(room.team_names),
                        "team_topics": dict(room.team_topics),
                    },
                })

            # ── set_team_info ─────────────────────────────────────────────────
            elif action == "set_team_info":
                if room.play_mode != PlayMode.TEAM:
                    continue
                name_a  = sanitize_string(msg.get("name_a",  room.team_names.get("A", "Team A")), MAX_TEAM_NAME) or "Team A"
                name_b  = sanitize_string(msg.get("name_b",  room.team_names.get("B", "Team B")), MAX_TEAM_NAME) or "Team B"
                # Validate topics through the injection filter
                raw_topic_a = msg.get("topic_a", "")
                raw_topic_b = msg.get("topic_b", "")
                topic_a, _ = validate_topic(raw_topic_a) if raw_topic_a else ("", None)
                topic_b, _ = validate_topic(raw_topic_b) if raw_topic_b else ("", None)
                room.team_names = {"A": name_a, "B": name_b}
                if topic_a:
                    room.team_topics["A"] = topic_a
                if topic_b:
                    room.team_topics["B"] = topic_b
                await broadcast(room_code, {
                    "type": "PLAYER_JOINED",
                    "data": {
                        "players":     list(room.players.keys()),
                        "lobby_mode":  room.play_mode.value,
                        "teams":       dict(room.teams),
                        "team_names":  dict(room.team_names),
                        "team_topics": dict(room.team_topics),
                    },
                })

            # ── pick_topic (duel) ─────────────────────────────────────────────
            elif action == "pick_topic":
                if room.play_mode != PlayMode.DUEL or room.status != GameStatus.WAITING:
                    continue
                picked = sanitize_string(msg.get("topic"), MAX_TOPIC_LEN)
                if picked not in room.duel_topic_options:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Pick one of the offered topics."},
                    })
                    continue
                if player_name in room.duel_picks:
                    continue
                room.duel_picks[player_name] = picked

                # The practice bot picks the moment the human does.
                if room.duel_is_bot and room.duel_bot_name not in room.duel_picks:
                    room.duel_picks[room.duel_bot_name] = random.choice(
                        room.duel_topic_options
                    )

                await broadcast(room_code, {
                    "type": "DUEL_PICKS_UPDATE",
                    "data": {"picks": dict(room.duel_picks)},
                })

                if len(room.duel_picks) >= 2:
                    picks = list(room.duel_picks.values())
                    if picks[0] == picks[1]:
                        room.topic = picks[0]
                        spin = False
                    else:
                        room.topic = random.choice(picks)
                        spin = True  # client reuses the Team randomizer spin UI
                    await broadcast(room_code, {
                        "type": "DUEL_TOPIC_RESOLVED",
                        "data": {
                            "topic":      room.topic,
                            "picks":      dict(room.duel_picks),
                            "spin":       spin,
                            "confirm_ms": 3500,
                        },
                    })
                    asyncio.create_task(_start_duel_game(room_code, delay=4.0 if spin else 3.5))

            # ── duel_rematch ──────────────────────────────────────────────────
            elif action == "duel_rematch":
                if room.play_mode != PlayMode.DUEL or room.status != GameStatus.FINISHED:
                    continue
                room.duel_rematch_votes.add(player_name)
                if room.duel_is_bot:
                    room.duel_rematch_votes.add(room.duel_bot_name)
                await broadcast(room_code, {
                    "type": "DUEL_REMATCH_UPDATE",
                    "data": {"votes": sorted(room.duel_rematch_votes)},
                })
                if len(room.duel_rematch_votes) >= 2:
                    # Same two players, fresh room state — skip matchmaking.
                    if not room.duel_is_bot:
                        broke = _insufficient_coin_names(room)
                        if broke:
                            await broadcast(room_code, {
                                "type": "ERROR",
                                "data": {"message": f"Not enough coins for a rematch: {', '.join(broke)}"},
                            })
                            room.duel_rematch_votes.clear()
                            continue
                    _reset_room_for_rematch(room)
                    await broadcast(room_code, {
                        "type": "DUEL_TOPIC_PICK",
                        "data": {
                            "options":       list(room.duel_topic_options),
                            "players":       list(room.players.keys()),
                            "bot_name":      room.duel_bot_name,
                            "time_limit_ms": room.time_limit_ms,
                        },
                    })

            # ── duel_reaction ─────────────────────────────────────────────────
            elif action == "duel_reaction":
                if room.play_mode != PlayMode.DUEL:
                    continue
                emoji = msg.get("emoji")
                # Preset-only reactions — deliberately not free text, so there
                # is nothing to moderate between strangers.
                if emoji not in ("👏", "😤", "🔥", "😂", "🤯"):
                    continue
                await broadcast(room_code, {
                    "type": "DUEL_REACTION",
                    "data": {"from": player_name, "emoji": emoji},
                })

            # ── use_powerup ───────────────────────────────────────────────────
            elif action == "use_powerup":
                # Only mid-question, and only before this player has answered —
                # power-ups modify the CURRENT answer, never a settled one.
                if room.status != GameStatus.ACTIVE or room.phase != RoundPhase.QUESTION:
                    continue
                pid = msg.get("powerup_id")
                if not isinstance(pid, str) or pid not in POWERUP_CATALOG:
                    continue
                if not allowed_in_mode(pid, room.play_mode.value):
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "That power-up can't be used in this mode."},
                    })
                    continue
                if player_name in room.answers_this_round:
                    continue
                round_key = f"{player_name}:{pid}"
                if round_key in room.round_powerups_used:
                    continue

                # Duel fairness caps: max 2 power-ups per match, no repeats.
                if room.play_mode == PlayMode.DUEL:
                    used = room.duel_powerups_used.setdefault(player_name, [])
                    if len(used) >= DUEL_MAX_POWERUPS_PER_MATCH:
                        await send_to(websocket, {
                            "type": "ERROR",
                            "data": {"message": f"Max {DUEL_MAX_POWERUPS_PER_MATCH} power-ups per duel."},
                        })
                        continue
                    if pid in used:
                        await send_to(websocket, {
                            "type": "ERROR",
                            "data": {"message": "You already used that power-up this duel."},
                        })
                        continue

                # Server-authoritative inventory spend (same trust model as the
                # rest of the user_id-keyed API surface).
                uid = room.players[player_name].user_id
                if not uid:
                    raw_uid = msg.get("user_id")
                    uid = raw_uid if isinstance(raw_uid, str) and raw_uid else None
                if not uid or not consume_powerup(uid, pid):
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "You don't own that power-up — grab it in the Shop!"},
                    })
                    continue

                room.round_powerups_used.add(round_key)
                if room.play_mode == PlayMode.DUEL:
                    room.duel_powerups_used.setdefault(player_name, []).append(pid)

                question = room.questions[room.current_q_index]
                if pid == "fifty_fifty":
                    wrong = [i for i in range(len(question.options)) if i != question.correct_index]
                    remove = random.sample(wrong, min(2, len(wrong)))
                    await send_to(websocket, {"type": "POWERUP_5050", "data": {"remove": remove}})
                elif pid == "time_freeze":
                    # Extend the server-side round timeout so the bonus seconds
                    # aren't eaten by the expiry task's fixed schedule.
                    room.round_extra_secs += FREEZE_BONUS_SECONDS
                    deadline = (
                        room.question_started_at
                        + (room.time_limit_ms / 1000)
                        + room.round_extra_secs
                        + 3  # same grace as _expire_question
                    )
                    _cancel_round_timeout(room_code)
                    _round_timeout_tasks[room_code] = asyncio.create_task(
                        _expire_question_in(room_code, room.current_q_index, deadline - time.time())
                    )
                    await send_to(websocket, {
                        "type": "POWERUP_FREEZE",
                        "data": {"seconds": FREEZE_BONUS_SECONDS},
                    })
                elif pid == "double_points":
                    room.double_points_active.add(player_name)
                    await send_to(websocket, {"type": "POWERUP_DOUBLE", "data": {}})
                elif pid == "time_steal":
                    opp = next((p for n, p in room.players.items() if n != player_name), None)
                    if opp is not None and opp.websocket is not None:
                        await send_to(opp.websocket, {
                            "type": "POWERUP_STEAL",
                            "data": {"from": player_name, "seconds": STEAL_SECONDS},
                        })

                # Everyone sees WHO used WHAT (stakes/drama, esp. duels) — but
                # never the effect internals (e.g. which options 50/50 removed).
                entry = POWERUP_CATALOG[pid]
                await broadcast(room_code, {
                    "type": "POWERUP_USED",
                    "data": {
                        "name": player_name,
                        "powerup_id": pid,
                        "label": entry["name"],
                        "icon": entry["icon"],
                    },
                })

            # ── start_game ────────────────────────────────────────────────────
            elif action == "start_game":
                if player_name != room.host:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Only the host can start the game"},
                    })
                    continue
                if room.status != GameStatus.WAITING:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Game already started"},
                    })
                    continue

                # Rate-limit quiz generation (uses last-IP)
                if is_rate_limited(ip, action="quiz"):
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Quiz generation limit reached. Wait a minute!"},
                    })
                    continue

                # Resolve play mode
                if room.play_mode != PlayMode.SOLO:
                    raw_pm = validate_play_mode(msg.get("play_mode"), allowed=("classic", "team"))
                    if raw_pm:
                        try:
                            room.play_mode = PlayMode(raw_pm)
                        except ValueError:
                            room.play_mode = PlayMode.CLASSIC

                if room.play_mode in (PlayMode.CLASSIC, PlayMode.TEAM):
                    broke_players = _insufficient_coin_names(room)
                    if broke_players:
                        await send_to(websocket, {
                            "type": "ERROR",
                            "data": {"message": f"Not enough coins: {', '.join(broke_players)}"},
                        })
                        continue
                    _charge_room_entry_fees(room)

                # Validate difficulty
                raw_mode = validate_game_mode(msg.get("mode"))
                if raw_mode:
                    try:
                        room.mode = GameMode(raw_mode)
                    except ValueError:
                        room.mode = DEFAULT_GAME_MODE
                else:
                    room.mode = DEFAULT_GAME_MODE
                room.time_limit_ms = time_limit_for_mode(room.mode)
                room.status        = GameStatus.STARTING

                # ── Topic resolution ──────────────────────────────────────────
                if room.play_mode == PlayMode.TEAM:
                    candidates = [t for t in room.team_topics.values() if t.strip()]
                    if not candidates:
                        topic          = "General Knowledge"
                        chosen_team_id: str | None = None
                    else:
                        topic          = random.choice(candidates)
                        chosen_team_id = next(
                            (tid for tid, t in room.team_topics.items() if t == topic), None
                        )
                    room.topic = topic
                else:
                    raw_topic = msg.get("topic", "General Knowledge")
                    topic, topic_err = validate_topic(raw_topic)
                    if topic_err:
                        # Refund any charged fees before bailing
                        if room.entry_fees:
                            _refund_room_entry_fees(room)
                        room.status = GameStatus.WAITING
                        await send_to(websocket, {
                            "type": "ERROR",
                            "data": {"message": topic_err},
                        })
                        continue
                    if not topic:
                        topic = "General Knowledge"
                    room.topic     = topic
                    chosen_team_id = None

                # ── Generation ticket gating (Milestone 39) ────────────────────
                # ANY topic that is not a bundled Quick Pick will call Gemini
                # and therefore costs real money. This gate applies regardless
                # of play mode (Solo included) — previously Solo mode had no
                # gate at all, which left the app open to unlimited free
                # Gemini calls from unauthenticated guests, protected only by
                # a weak, easily-bypassed per-IP rate limit.
                #
                # Quick Pick topics remain free and sign-in-free in every mode.
                if not is_quick_pick_topic(topic):
                    host_player = room.players.get(room.host)
                    if not host_player or not host_player.user_id:
                        if room.entry_fees:
                            _refund_room_entry_fees(room)
                        room.status = GameStatus.WAITING
                        await send_to(websocket, {
                            "type": "ERROR",
                            "data": {
                                "message": "Sign in with Google to play a custom AI topic. "
                                           "Quick Pick topics are free to play without signing in."
                            },
                        })
                        continue
                    try:
                        generation_result = use_generation(host_player.user_id)
                        room.generation_ticket_user_id = host_player.user_id
                        room.generation_source = generation_result["source"]
                    except TicketError:
                        if room.entry_fees:
                            _refund_room_entry_fees(room)
                        room.status = GameStatus.WAITING
                        await send_to(websocket, {
                            "type": "ERROR",
                            "data": {
                                "message": "Out of free generations and tickets today. Play a Quick "
                                           "Pick topic for free, buy tickets in the Shop, or come "
                                           "back tomorrow."
                            },
                        })
                        continue

                starting_data: dict[str, Any] = {
                    "topic":           topic,
                    "mode":            room.mode.value,
                    "play_mode":       room.play_mode.value,
                    "time_limit_ms":   room.time_limit_ms,
                    "total_questions": 10,
                }
                if room.play_mode == PlayMode.TEAM:
                    starting_data["chosen_team_id"] = chosen_team_id
                    starting_data["team_names"]     = dict(room.team_names)
                    starting_data["team_topics"]    = dict(room.team_topics)
                    starting_data["teams"]          = dict(room.teams)

                await broadcast(room_code, {"type": "GAME_STARTING", "data": starting_data})

                # ── Generate questions ────────────────────────────────────
                # Quick Pick topics are served from the static bank (zero
                # Gemini cost, zero rate-limit pressure) whenever the bank
                # has enough questions for this topic. Falls back to live
                # Gemini generation transparently if the bank is missing or
                # thin for this specific topic — a game must never fail to
                # start just because the bank isn't fully populated yet.
                served_from_bank = False
                if is_quick_pick_topic(topic):
                    try:
                        room.questions = get_quick_pick_questions(topic)
                        served_from_bank = True
                    except ValueError as exc:
                        logger.info(
                            "Quick Picks bank unavailable for '%s' (%s) — falling back to Gemini",
                            topic, exc,
                        )

                if not served_from_bank:
                    try:
                        room.questions = await asyncio.wait_for(
                            generate_questions(topic),
                            timeout=GENERATION_TIMEOUT_SECONDS,
                        )
                    except asyncio.TimeoutError:
                        logger.warning(
                            "Question generation timed out for room '%s'; using fallback", room_code
                        )
                        room.questions = [Question(**q) for q in FALLBACK_QUESTIONS]
                    except Exception as exc:
                        logger.error(
                            "Question generation failed for room '%s': %s", room_code, exc
                        )
                        if room.entry_fees:
                            _refund_room_entry_fees(room)
                        _refund_generation_ticket(room)
                        room.status = GameStatus.WAITING
                        room.phase  = RoundPhase.LOBBY
                        await broadcast(room_code, {
                            "type": "ERROR",
                            "data": {"message": "Failed to generate questions. Try again."},
                        })
                        continue

                for p in room.players.values():
                    p.score = 0; p.correct_answers = 0; p.streak = 0
                room.status          = GameStatus.ACTIVE
                room.current_q_index = 0
                await broadcast_question(room_code)

            # ── answer ────────────────────────────────────────────────────────
            elif action == "answer":
                if room.status != GameStatus.ACTIVE or room.phase != RoundPhase.QUESTION:
                    continue
                if player_name in room.answers_this_round:
                    continue

                choice = validate_choice(msg.get("choice"))
                if choice is None:
                    await send_to(websocket, {
                        "type": "ERROR",
                        "data": {"message": "Invalid answer choice"},
                    })
                    continue

                time_ms  = validate_time_ms(msg.get("time_ms"), room.time_limit_ms)
                question = room.questions[room.current_q_index]
                is_correct = choice == question.correct_index
                player     = room.players[player_name]

                if is_correct:
                    player.streak += 1
                    if room.play_mode == PlayMode.DUEL:
                        points, tier = calculate_duel_score(time_ms, room.time_limit_ms)
                        if _duel_is_final_stretch(room):
                            points *= DUEL_FINAL_STRETCH_MUL
                        room.round_speed_tiers[player_name] = tier
                    else:
                        points = calculate_score(time_ms, room.time_limit_ms, player.streak)
                    player.correct_answers += 1
                else:
                    player.streak = 0
                    points = 0

                # DOUBLE_POINTS power-up: one-shot 2x on this question's answer.
                # Consumed whether the answer was right or wrong — it was armed
                # for this answer, not banked until a correct one lands.
                if player_name in room.double_points_active:
                    room.double_points_active.discard(player_name)
                    if is_correct:
                        points *= 2

                player.score      += points
                player.answered    = True
                player.last_answer = choice
                room.answers_this_round[player_name] = choice
                room.points_gained[player_name]      = points

                # Live "opponent locked in" cue for duels — reveals only THAT a
                # player answered, never the choice or correctness, so it can't
                # leak the answer to the still-thinking opponent.
                if room.play_mode == PlayMode.DUEL:
                    await broadcast(room_code, {
                        "type": "DUEL_PLAYER_ANSWERED",
                        "data": {"name": player_name},
                    })

                connected = _connected_players(room)
                if len(room.answers_this_round) >= _required_answer_count(room):
                    # Cancel the expire task BEFORE calling resolve_round so we
                    # don't race: expire fires at roughly the same instant the
                    # last answer arrives, and without this cancel both paths
                    # would enter resolve_round concurrently.
                    _cancel_round_timeout(room_code)
                    await resolve_round(room_code, room.current_q_index)

    except WebSocketDisconnect:
        player = room.players.get(player_name)
        if player:
            player.websocket = None
        logger.info("Player '%s' disconnected from room '%s'", player_name, room_code)

        any_connected = any(p.websocket is not None for p in room.players.values())
        if any_connected:
            # ── Duel forfeit ──────────────────────────────────────────────────
            # Head-to-head has no "play on without them": if the leaver does
            # not reconnect within the grace window, the player who stayed
            # wins the pot outright. Grace matches the client's auto-reconnect
            # ladder so a flaky network never insta-loses a duel.
            if (
                room.play_mode == PlayMode.DUEL
                and not room.duel_is_bot
                and room.status == GameStatus.ACTIVE
            ):
                asyncio.create_task(_duel_forfeit_check(room_code, player_name))

            dc_data: dict[str, Any] = {
                "players":    list(room.players.keys()),
                "lobby_mode": room.play_mode.value,
            }
            if room.play_mode == PlayMode.TEAM:
                dc_data["teams"]       = dict(room.teams)
                dc_data["team_names"]  = dict(room.team_names)
                dc_data["team_topics"] = dict(room.team_topics)
            await broadcast(room_code, {"type": "PLAYER_JOINED", "data": dc_data})

            connected = _connected_players(room)
            if (
                room.status == GameStatus.ACTIVE
                and room.phase == RoundPhase.QUESTION
                and len(room.answers_this_round) >= len(connected)
            ):
                # Same cancel-before-resolve discipline as the answer handler.
                # A disconnecting player can trigger this path at the same time
                # the expire_question task fires, causing a duplicate resolve.
                _cancel_round_timeout(room_code)
                asyncio.create_task(resolve_round(room_code, room.current_q_index))
        else:
            asyncio.create_task(_delayed_room_cleanup(room_code))
